config/routes.rb
Project::Application.routes.draw do
  root 'welcome#index'
  get "welcome/index"
  devise_for :users

  resources :users
  resources :friendships
  resources :circles
  resources :circles_friends

  match 'show', to: 'welcome#show', via: [:get, :post]
  match 'add_friend', to: 'friendships#add_friend', via: [:get, :post]
  match ':controller/:action/:id', via: [:get, :post]
  match 'create_circle', to: 'welcome#create_circle', via: [:get, :post]
  match 'add_to_circle', to: 'welcome#add_to_circle', via: [:get, :post]
  match 'delete_from_circle', to: 'welcome#delete_from_circle', via: [:get, :post]
  match 'circle_friend', to: 'welcome#circle_friend', via: [:get, :post]

  

end

app/models/circle.rb
class Circle < ActiveRecord::Base
	has_and_belongs_to_many :users
	belongs_to :user
	validates :circle_name, presence: true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_and_belongs_to_many :members , :class_name => "Circle"
  has_many :circles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
  @friendship = current_user.friendships.build(:friend_id => params[:friend_id],:status=>0)

  if @friendship.save
    
     redirect_to action: 'show', controller: "welcome"
  else
    flash[:error] = "Unable to add friend!"
    redirect_to root_path
  end
end
def add_friend
  @friendship = Friendship.where(:user_id=>params[:id],:friend_id=>current_user.id).first
  @friendship.update_attribute(:status ,1)

    flash[:notice] = "Accepted friend!"
    redirect_to root_path


end
def reject_friend
  @friendship = Friendship.where(:user_id=>params[:id],:friend_id=>current_user.id).first
  
    flash[:notice] = "Rejected friend!"
  @friendship.destroy
    redirect_to root_path  
end

def block_friend

  @friendship = Friendship.where(:user_id=>params[:id],:friend_id=>current_user.id).first
    @friendship.update_attribute(:status ,2)
    flash[:notice] = "Blocked friend!"
  redirect_to root_path
end
def destroy
  @friendship = Friendship.find(params[:id])
   @friendship.destroy
  redirect_to root_path
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 before_filter :authenticate_user!
 def index
  @notcurrent=User.where.not(:id => current_user.id)
  @users=User.all
  @friendships1=current_user.friendships.map {|a| a.friend_id}
  @user=current_user
  @circles=Circle.where(:user_id => current_user)
end
def show
 @user=current_user
 @circles=Circle.where(:user_id => current_user.id)
 end
def new
  @user=User.new
  @circle=Circle.new

end 

def create_circle
  @circle = Circle.new(circle_params)
  if @circle.save
    flash[:error] = "Created Circle!"
    redirect_to root_path

  else
    flash[:error] = "Unable to add friend!"
    redirect_to root_path
  end
end

def delete_circle
  @cir=Circle.find(params[:id])
    @cir.destroy
    redirect_to root_path
  end

def add_to_circle
 @user = User.find(params[:friend_id])
@circles = Circle.find(params[:circle_id])
@circles.users << @user
 if @circles.save
    flash[:error] = "Added to Circle!"
    redirect_to root_path

  else
    flash[:error] = "Unable to add friend!"
    redirect_to root_path
  end
end

def delete_from_circle
  @user=User.find(params[:friend_id])
  @circles = Circle.find(params[:id])
  @circles.users.delete(@user)
  redirect_to root_path
end
def circle_params
  params.require(:circle).permit(:user_id,:circle_name)
end
def circle_friend
  @cirfrens=Circle.where(:id => params[:id],:circle_name =>params[:name])
  @d=User.where(:id=>current_user.id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Project</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	<div class="col-xs-12 sign">
	Signed in as <%= current_user.email %>
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
	<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
	</div>
	<% end %>
	<%= yield %>

</body>
</html>

app/views/welcome/circle_friend.html.erb
<% for cirfr in @cirfrens%>
<h3>Friends in Circle: <%= "#{cirfr.circle_name}"%></h3>
  	<%cirfr.users.each do |s| %>
  	<%= s.email%><br/> 
<%end%>
<%end%>

app/views/welcome/create_circle.html.erb
<h1>New Circle</h1>
<%= form_for @circle, :url => { :action => "create_circle" }  do |f|  %>
	<%= f.hidden_field :user_id, :value =>current_user.id%>
    <%= f.text_field  :circle_name %>

    <%= f.submit "Create Circle", class: "btn btn-primary" %>
 <%end%>

<%= link_to 'Back', root_path %>

app/views/welcome/index.html.erb
<div class="container">
	<div class="row" id="user_nav">

		<% if flash[:notice]%>
		<%= flash[:notice] %>
		<%end%>      	
	</div>
	<div>
		<div>
			<strong><%= link_to "View Friends", :controller => "welcome" , :action =>"show" %></strong>
		</div>
		<h3>Friend Requests</h3><br/>
		<% @a=Friendship.where(:friend_id => current_user.id, :status => 0) %>
		<% @a.each do |f1|%>
		<%= f1.user.email%>
		<%= link_to "Add", :controller=> "friendships", :action=> "add_friend", :id => f1.user_id %>
		<%= link_to "Reject", :controller=> "friendships", :action=> "reject_friend", :id => f1.user_id%>
		<%= link_to "Block", :controller=> "friendships", :action=> "block_friend", :id => f1.user_id %>

		<%end%>
	</div>
	<br/><br/>
	<h3>Other Users</h3>

	<div class="row user-list">
		<div class="col-xs-12 user">
				<% @notcurrent.each do |u|%>
					<% if Friendship.where(['(user_id = ? AND friend_id = ?) OR (user_id = ? AND friend_id = ?)', current_user.id, u.id, u.id, current_user.id]).count <= 0 %>
					<%= u.email %><%= link_to "Add Friend", friendships_path(:friend_id => u.id), :method => :post %><br/>
					<% end %>
				<%end%>
		   	    <% @a1=Friendship.where(:friend_id => current_user.id)%>
				<% @a2=Friendship.where(:user_id => current_user.id) %>
					<% @a1.each do |a|%>
						<%= User.find(a.user_id).email%>
						<% if a.status == 0 %>
							<%= link_to "Request Sent"%><br/>
						<%elsif a.status == 2 %>
							Blocked user<br/>
						<%elsif a.status == 1 %>
							Accepted Request<br/>
					
						<%end%>
					<%end%>
					<% @a2.each do |a|%>
						<%= User.find(a.friend_id).email%>

						<% if a.status == 0 %>
							<%= link_to "Request Sent"%><br/>
						<%elsif a.status == 2 %>
							Blocked user<br/>
						<%elsif a.status == 1 %>
							Friends<br/>
						<%end%>
					<%end%>
					
		</div>
	</div>

	<div class="row circle-list">
		<div class="col-xs-12">
		<h3>Your existing Circles</h3>
			<% @circles.each do |c| %>
			<%=c.circle_name%>
			<%= link_to(" : Friends in this Circle", :controller => "welcome" , :action =>"circle_friend",:id => c.id,:name => c.circle_name)%><br/>
			<%= link_to("Delete this Circle", :controller =>"welcome", :action => "delete_circle", :id=> c.id) %><br/>
			<%end%>
			

			<h3>Create new Circle</h3>

			<%= form_for :circle, :url => { :controller => "welcome", :action => "create_circle", :method => "POST" }  do |f|  %>
			<%= f.hidden_field :user_id, :value =>current_user.id%>
			<%= f.text_field  :circle_name %>
			<%= f.submit "Create Circle", class: "btn btn-primary" %>
			<%end%>
		</div>
	</div>


</div>

app/views/welcome/show.html.erb
<p><%= link_to "Back", root_path %></p>
<h3>Sent Request</h3><br/>
<% @cufs=@user.friendships %>
<% @a= @cufs.where(:status =>0) %>
<% for friendship in @a %>
	<%= friendship.friend.email%> :: 
	<%= link_to "Cancel Request", friendship, :method =>:delete %><br/>
<%end%>

<h3>Friends</h3>
<% @cufs1=@user.friendships %>
<% @a1= @cufs1.where(:status =>1) %>
<% for friendship in @a1%>
	<br/><strong><%= friendship.friend.email%> :: </strong><br/>
	<%= link_to "Unfriend", friendship, :method =>:delete %><br/>
	<% @circles.each do |c|%>
		<% @u = User.find(friendship.friend_id) %>
		<% @c = Circle.find(c.id) %>
			<% if c.users.include?(@u) %>
				<%= link_to("Delete from circle", :controller => "welcome" , :action =>"delete_from_circle",:friend_id => friendship.friend_id,:id=>c.id,:method => 'delete')%><%= ": #{c.circle_name}"%><br/>
			<%else%>
				<%= link_to("Add to circle", :controller => "welcome", :action =>"add_to_circle" ,:circle_id=> c.id,:friend_id => friendship.friend_id) %><%= " : #{c.circle_name}"%><br/>
			<%end%>
	<%end%>
<%end%>

<% @b1=Friendship.where(:friend_id => current_user.id, :status=>1)%>
<% for friendship in @b1%>
	<% @u= User.where(:id =>friendship.user_id).first%>
	<br/><strong><%= @u.email%> :: </strong><br/>
	<%= link_to "Unfriend", friendship, :method =>:delete %><br/>
		<% @circles.each do |c|%>
			<% @u = User.find(friendship.user_id) %>
			<% @c = Circle.find(c.id) %>
				<% if c.users.include?(@u) %>
				<%= link_to("Delete from circle", :controller => "welcome" , :action =>"delete_from_circle",:friend_id => friendship.user_id, :id =>c.id, :method=>'delete')%><%= ": #{c.circle_name}"%><br/>
			<%else%>
				<%= link_to("Add to circle", :controller => "welcome", :action =>"add_to_circle" , :circle_id=>c.id,:friend_id => friendship.user_id)%><%= " : #{c.circle_name}"%><br/>
			<%end%>
		<%end%>
<%end%>